# Site Settings
locale                   : "en-US"
title                    : "Master of Science in Machine Learning & Artificial Intelligence"
title_separator          : "-"
name                     : &name "Tom Mathews"
description              : &description "personal description"
url                      : https://mathews-tom.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "MSc_in_Machine_Learning_and_Artificial_Intelligence" # the subpath of your site, e.g. "/blog"
repository               : "Mathews-Tom/MSc_in_Machine_Learning_and_Artificial_Intelligence"
theme                    : jekyll-theme-cayman

